language:
  node_js
node_js:
  - "stable"
services:
  - mongodb
before_script:
  - mongo mydb_test --eval 'db.createUser({user:"davidh",pwd:"lalocal",roles:["readWrite"]});'
script:
  - npm run test
after_script:
  - npm run report-coverage
  - codecov
